### ISSUE TITLE
AttributeError: module 'aiger_coins' has no attribute 'MDP'

### ISSUE THREAD

**Issue by NotEnded99** [mvcisback/mce-spec-inference#1]
When I run experiment.py, I encounter the following problem:
AttributeError: module 'aiger_coins' has no attribute 'MDP'
AttributeError: module 'aiger_coins' has no attribute 'coin'

**Comment by mvcisback** [comment]
hi @NotEnded99 ,

How did you download the dependencies? Using poetry? I would check you have the same versions as in the lock file, since the upstream packages had some major rewrites.

**Comment by NotEnded99** [comment]
> hi @NotEnded99 ,
> 
> How did you download the dependencies? Using poetry? I would check you have the same versions as in the lock file, since the upstream packages had some major rewrites.

I solved the problem by installing the correct version of the py-aiger-coins package. Thank you very much!
